# Poker hand statistics
ROYAL_FLUSH_HANDS = 4
STRAIGHT_FLUSH_HANDS = 36
FOUR_OF_A_KIND_HANDS = 624
FULL_HOUSE_HANDS = 3744
FLUSH_HANDS = 5108
STRAIGHT_HANDS = 10200
THREE_OF_A_KIND_HANDS = 54912
TWO_PAIR_HANDS = 123552
ONE_PAIR_HANDS = 1098240
HIGH_CARD_HANDS = 1302540
ALL_POKER_HANDS = 2598960

# Odds strings
ROYAL_FLUSH_ODDS = "650,000 to 1"
STRAIGHT_FLUSH_ODDS = "72,000 to 1"
FOUR_OF_A_KIND_ODDS = "4,000 to 1"
FULL_HOUSE_ODDS = "700 to 1"
FLUSH_ODDS = "500 to 1"
STRAIGHT_ODDS = "250 to 1"
THREE_OF_A_KIND_ODDS = "50 to 1"
TWO_PAIR_ODDS = "20 to 1"
ONE_PAIR_ODDS = "10 to 6"
HIGH_CARD_ODDS = "2 to 1"

# Hands beaten calculations
ROYAL_FLUSH_BEATS = ALL_POKER_HANDS - ROYAL_FLUSH_HANDS
STRAIGHT_FLUSH_BEATS = ROYAL_FLUSH_BEATS - STRAIGHT_FLUSH_HANDS
FOUR_OF_A_KIND_BEATS = STRAIGHT_FLUSH_BEATS - FOUR_OF_A_KIND_HANDS
FULL_HOUSE_BEATS = FOUR_OF_A_KIND_BEATS - FULL_HOUSE_HANDS
FLUSH_BEATS = FULL_HOUSE_BEATS - FLUSH_HANDS
STRAIGHT_BEATS = FLUSH_BEATS - STRAIGHT_HANDS
THREE_OF_A_KIND_BEATS = STRAIGHT_BEATS - THREE_OF_A_KIND_HANDS
TWO_PAIR_BEATS = THREE_OF_A_KIND_BEATS - TWO_PAIR_HANDS
ONE_PAIR_BEATS = TWO_PAIR_BEATS - ONE_PAIR_HANDS
HIGH_CARD_BEATS = ONE_PAIR_BEATS - HIGH_CARD_HANDS

# Probabilities
ROYAL_FLUSH_PROBABILITY = ROYAL_FLUSH_HANDS / ALL_POKER_HANDS
STRAIGHT_FLUSH_PROBABILITY = STRAIGHT_FLUSH_HANDS / ALL_POKER_HANDS
FOUR_OF_A_KIND_PROBABILITY = FOUR_OF_A_KIND_HANDS / ALL_POKER_HANDS
FULL_HOUSE_PROBABILITY = FULL_HOUSE_HANDS / ALL_POKER_HANDS
FLUSH_PROBABILITY = FLUSH_HANDS / ALL_POKER_HANDS
STRAIGHT_PROBABILITY = STRAIGHT_HANDS / ALL_POKER_HANDS
THREE_OF_A_KIND_PROBABILITY = THREE_OF_A_KIND_HANDS / ALL_POKER_HANDS
TWO_PAIR_PROBABILITY = TWO_PAIR_HANDS / ALL_POKER_HANDS
ONE_PAIR_PROBABILITY = ONE_PAIR_HANDS / ALL_POKER_HANDS
HIGH_CARD_PROBABILITY = ALL_POKER_HANDS / ALL_POKER_HANDS

# Triple hand statistics
ROYAL_FLUSH_TRIPLES = 4
STRAIGHT_FLUSH_TRIPLES = 48
THREE_OF_A_KIND_TRIPLES = 52
STRAIGHT_TRIPLES = 720
FLUSH_TRIPLES = 1144
PAIR_TRIPLES = 3692
HIGH_TRIPLES = 18356
ALL_TRIPLES = 22100

# Triple odds
ROYAL_FLUSH_TRIPLE_ODDS = "5,500 to 1"
STRAIGHT_FLUSH_TRIPLE_ODDS = "460 to 1"
THREE_OF_A_KIND_TRIPLE_ODDS = "425 to 1"
STRAIGHT_TRIPLE_ODDS = "30 to 1"
FLUSH_TRIPLE_ODDS = "20 to 1"
PAIR_TRIPLE_ODDS = "6 to 1"
HIGH_TRIPLE_ODDS = "4 out of 5"

# Triple beats calculations
ROYAL_FLUSH_TRIPLE_BEATS = ALL_TRIPLES - ROYAL_FLUSH_TRIPLES
STRAIGHT_FLUSH_TRIPLE_BEATS = ALL_TRIPLES - STRAIGHT_TRIPLES
THREE_OF_A_KIND_TRIPLE_BEATS = ALL_TRIPLES - THREE_OF_A_KIND_TRIPLES
STRAIGHT_TRIPLE_BEATS = ALL_TRIPLES - STRAIGHT_TRIPLES
FLUSH_TRIPLE_BEATS = ALL_TRIPLES - FLUSH_TRIPLES
PAIR_BEATS = ALL_TRIPLES - PAIR_TRIPLES
HIGH_TRIPLE_BEATS = ALL_TRIPLES - HIGH_TRIPLES

# Triple probabilities
ROYAL_FLUSH_TRIPLE_PROB = ROYAL_FLUSH_TRIPLES / ALL_TRIPLES
STRAIGHT_FLUSH_TRIPLE_PROB = STRAIGHT_FLUSH_TRIPLES / ALL_TRIPLES
THREE_OF_A_KIND_TRIPLE_PROB = THREE_OF_A_KIND_TRIPLES / ALL_TRIPLES
STRAIGHT_TRIPLE_PROBABILITY = STRAIGHT_TRIPLES / ALL_TRIPLES
FLUSH_TRIPLE_PROBABILITY = FLUSH_TRIPLES / ALL_TRIPLES
PAIR_PROBABILITY = PAIR_TRIPLES / ALL_TRIPLES
HIGH_TRIPLE_PROBABILITY = HIGH_TRIPLES / ALL_TRIPLES
